# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 16:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_jobs', '0004_auto_20190307_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_jobs.JobCategory'),
        ),
        migrations.AlterField(
            model_name='jobopeningtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_jobs.JobOpening'),
        ),
    ]
