# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 11:43
from __future__ import unicode_literals

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('aldryn_jobs', '0004_add_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNewsletterRegistrationPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_jobs_jobnewsletterregistrationplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, unique=True, verbose_name='recipient')),
                ('default_language', models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English'), ('zh', 'Chinese')], default='', max_length=32, verbose_name='language')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('confirmation_key', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSignupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='aldryn_jobs.NewsletterSignup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_signup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobsconfig',
            name='placeholder_jobs_newsletter_registration',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aldryn_jobs_newsletter_registration', slotname='jobs_newsletter_registration', to='cms.Placeholder'),
        ),
        migrations.AlterField(
            model_name='jobcategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_jobs.JobCategory'),
        ),
        migrations.AlterField(
            model_name='jobopeningtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_jobs.JobOpening'),
        ),
        migrations.AlterField(
            model_name='jobsconfig',
            name='namespace',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace'),
        ),
        migrations.AlterField(
            model_name='jobsconfig',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='app_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_jobs.JobsConfig', verbose_name='app_config'),
        ),
        migrations.AddField(
            model_name='jobnewsletterregistrationplugin',
            name='app_config',
            field=models.ForeignKey(help_text='Select appropriate add-on configuration for this plugin.', null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_jobs.JobsConfig', verbose_name='app_config'),
        ),
        migrations.AddField(
            model_name='jobnewsletterregistrationplugin',
            name='mail_to_group',
            field=models.ManyToManyField(blank=True, help_text='If user successfuly completed registration.<br/>Notification would be sent to users from selected groups<br/>Leave blank to disable notifications.<br/>', to='auth.Group', verbose_name='Notification to'),
        ),
    ]
