# Generated by Django 2.2.12 on 2020-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_jobs', '0007_auto_20201124_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='salutation',
            field=models.CharField(blank=True, choices=[('', 'Please select'), ('male', 'Mr.'), ('female', 'Mrs.')], max_length=20, null=True, verbose_name='salutation'),
        ),
    ]
