# Generated by Django 2.2.12 on 2020-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_jobs', '0009_auto_20201204_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='how_hear_about_us_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='other (how did you hear about us)'),
        ),
    ]
