# Generated by Django 2.2.12 on 2021-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_jobs', '0011_jobopeningtranslation_hide_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='abc_analysis',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC')], max_length=2, null=True, verbose_name='abc analysis'),
        ),
    ]
