# Generated by Django 2.2.12 on 2021-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_jobs', '0012_auto_20210504_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='abc_analysis',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('C', 'C')], max_length=2, null=True, verbose_name='abc analysis'),
        ),
    ]
