# Generated by Django 2.2.12 on 2021-05-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_jobs', '0013_auto_20210518_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopeningtranslation',
            name='meta_description',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='meta description'),
        ),
    ]
